# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200, verbose_name='图片')),
            ],
            options={
                'verbose_name': '底部图片',
                'verbose_name_plural': '底部图片',
            },
        ),
        migrations.AlterModelOptions(
            name='blogposts',
            options={'verbose_name': '主页内容', 'verbose_name_plural': '主页内容'},
        ),
    ]
