# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-28 00:35
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
