# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('mail', '男'), ('fmail', '女')], max_length=5, verbose_name='性别')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
    ]
